---
- name: Reset previous kubeadm state
  shell: kubeadm reset -f
  ignore_errors: true

- name: Join Workers
  vars:
    join_worker: "{{ lookup('file', '/tmp/kubeadm-join-worker.txt') }}"
  shell: "export KUBELET_EXTRA_ARGS=\"--cloud-provider=external\" && {{ join_worker }}"