---
- name: Ensure CRI-O is running
  systemd_service:
    name: crio
    state: started
    enabled: true

- name: KubeAdm Reset (cleanup previous init)
  shell: kubeadm reset -f
  ignore_errors: true

- name: KubeAdm Init
  shell: kubeadm init --config /home/admin/kubeadm-init.yml
  register: kubeadm_init_output

- name: KubeAdm Init (Output)
  debug:
    var: kubeadm_init_output.stdout_lines