---
- name: Terraform Output
  shell: terraform output -json > outputs.json
  args:
    chdir: "{{terraform_path}}/server"
  delegate_to: localhost
  environment:
    AWS_REGION: "{{aws_region}}"
    AWS_ACESS_KEY: "{{aws_access_key}}"
    AWS_SECRET_ACCESS_KEY: "{{aws_secret_access_key}}"
    AWS_PROFILE: "{{aws_profile}}"

- name: Get NLB DNS name
  vars:
    terraform_outputs: "{{ lookup('file', '{{terraform_path}}/server/outputs.json') }}"
    nlb_dns_name: "{{ terraform_outputs.nlb_dns_name.value }}"
  debug:
    var: nlb_dns_name